CREATE TABLE IF NOT EXISTS readers (
    readerID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    bookID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    pages INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rents (
    rentID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    readerID INTEGER NOT NULL REFERENCES readers(readerID),
    bookID INTEGER NOT NULL REFERENCES books(bookID),
    startDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    endDate TIMESTAMP
);